### ISSUE TITLE
reviews.csv must be renammed to review.csv or script updated

### ISSUE THREAD

**Issue by moses3009** [SAP-samples/datahub-dine#1]
In documentation  and in script it is used review.csv but the file is named reviews.csv. Either rename the file, or update the script and configs for Read File operator. This is related to Sentiment Analyser example.

**Comment by ANUGRAHG** [comment]
Updated the document.

Thanks.

**Comment by moses3009** [comment]
scripts is still with review.csv, so it will fail

**Comment by ANUGRAHG** [comment]
In the script section, we have created a temporary "review.csv" file from dataframe at line 15, which we are using at line 18. This file is not related to the file which we are reading using ReadFile operator. So script will work as expected.
