### ISSUE TITLE
Sentiment Analyser - python2operator2 wrong output port

### ISSUE THREAD

**Issue by moses3009** [SAP-samples/datahub-dine#2]
Sentiment Analyser - python2operator2 wrong output port -> according documentation, output port is named output, but in script it is used output1 name. This cause failure of the graph.

**Comment by ANUGRAHG** [comment]
Hi,

I checked the documentation and found that output port name for python2operator2 is named as "output1" only. See Step 37.  Hope this helps.

Thanks
