### ISSUE TITLE
tutorial - Incorrect link reference

### ISSUE THREAD

**Issue by ihenry** [SAP-samples/datahub-dine#3]
The link in the Readme.md to the tutorial is incorrect. 

It refers to the internal github https://github.wdf.sap.corp/refapps/datahub-dine/tree/master/tutorials/customer%20return%20prediction
when it should point to https://github.com/SAP/datahub-dine/tree/master/tutorials/customer%20return%20prediction

**Comment by pushkargd** [comment]
Issue resolved
